services:
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - '15672:15672'
    restart: unless-stopped
    container_name: rabbitmq
  spring_boot_producer:
    container_name: spring_boot_producer
    build:
      context: ./java_spring_producer
      dockerfile: ./Dockerfile
